### ISSUE TITLE
Possibility to use 1 MCU for both halves.

### ISSUE THREAD

**Issue by azhizhinov** [rgoulter/keyboard-labs#3]
Hello.
I'm not so talented engineer as you, so asking. :-)
Is it possible to use only 1 MCU?
Something like this project?
https://github.com/SzymonGoldberg/scsbaf40
Thanks in advance.

**Comment by rgoulter** [comment]
May be possible, but it's arguable whether it's worth it.

The "X-1" design in this repository works in the same style as the [helix keyboard](https://github.com/MakotoKurauchi/helix) (or its more famous descendant, [the corne](https://github.com/foostan/crkbd)). It communicates using TRRS (Tip Ring Ring Sleeve) cable. The cable provides 5V / GND, and 2 wires for communication (either TX/RX or Clock/Data) between micro controller dev boards on each side.

The approach taken by scsbaf40 is to use an RJ45 jack. The RJ45 provides 8 wires. I haven't looked at the scsbaf40's schematic, but you can see the RHS has 16 switches <-> 4 rows x 4 columns <-> 4 wires + 4 wires. -- I mean, 16 keys is the max supported by the ethernet cable.

Applying that idea to this "X-1" design:

- My "X-1" design has 18 switches on each side, plus the RGB LEDs (which need the 5V, GND, and the RGB data). So, you'd either need some cable with more wires, or to strip the fancy features.

- The "X-1" design was space-constrained to "under 100x100mm" and "reversible". This meant can just use a promotion procie at e.g. JLCPCB without having to pay more. At a glance, it looks like the scsbaf40 uses different PCBs per side, and is larger than 100x100mm.
  - The TRRS jack is probably about the smallest connector you can fit in the spirit of this design. The jacks for bigger cables make the PCB bigger.
  - My design saves money on the PCBs, but has more expensive MCU dev boards; scsbaf40's is the opposite. (These MCU devboards are about $3 - $7, and non-promo 100x100mm PCBs are about $6 for the minimum 5pc).

If you're uncertain, it's probably worth trying out with an MCU, some bread boards, and some breakout boards for the connectors you want to try. -- Designing a split keyboard in a way that doesn't copy from others might not be the most practical, but it seems like it'd be fun.

**Comment by azhizhinov** [comment]
Grate.
Thanks for your answer.
I can understand that, 8 wires gives us 4x4 matrix. :-)
But maybe UCB-C cable can be used as here.
https://github.com/KarlK90/yaemk-split-kb
I'm totally dumb in those MCU things, signals, programming...
But I can drag lines in KiCAD. :-)
Have a nice day.
