### ISSUE TITLE
Can I2C external EEPROM be used at the same pin with the OLED on Blackpill?

### ISSUE THREAD

**Issue by vinhcatba** [rgoulter/keyboard-labs#5]
I am wondering if the 2 I2C devices (OLED and EEPROM) can share the same pin on STM32F401 Blackpill without any problem?

**Comment by rgoulter** [comment]
Easiest way to check would be to get a breadboard & maybe some breakout boards for the components you want to check.

If you have to ask, you're probably going to make a mistake; and it's better to make a mistake with a breadboard (where it's easy to change things) than with a PCB using a devboard.

**Comment by rgoulter** [comment]
Anyway, I would think that I2C would be able to work with multiple devices from the same pin, so long as those devices don't conflict on what address they use, IIRC.

**Comment by vinhcatba** [comment]
thanks, I will test with breadboard ASA my Blackpill arrives.
